### ISSUE TITLE
Do not exclude seeders in calculateChecksum when refresh_db_fast.seed is enabled

### ISSUE THREAD

**Issue by V35CH** [laracraft-tech/laravel-useful-additions#13]
When refresh_db_fast.seed is enabled, the seeders folder should not be excluded for checksum calculation. So when there is a change in seeders, the db should be seeded on the next test run.

See Patch File:
[seeder.patch](https://github.com/laracraft-tech/laravel-useful-additions/files/14930266/seeder.patch)

**Comment by V35CH** [comment]
Or I think it is better to use the method `$this->shouldSeed()` to determine to seed or not. See: `\Illuminate\Foundation\Testing\Traits\CanConfigureMigrationCommands`
So we don't need the config anymore.
And you can also drop `$this->seed()` in `runMigrationsIfNecessary()`

See Patch File:
[seeder.patch](https://github.com/laracraft-tech/laravel-useful-additions/files/14930607/seeder.patch)

**Comment by Sairahcaz** [comment]
Hi @V35CH, thanks for contributing! Could maybe create a PR for that?
I'm a bit cautious about downloading unfamiliar files onto my computer...
